- name: install httpd
  yum: name=httpd state=latest

- name: add vagrant group to apache
  command: usermod -G vagrant apache

- name: start httpd and enabled
  service: name=httpd state=started enabled=yes

- name: configure httpd conf
  template: src=httpd.conf dest=/etc/httpd/conf/httpd.conf
  notify: restart apache

- name: configure php conf
  template: src=php.conf dest=/etc/httpd/conf.d/php.conf
  notify: restart apache