- name: stop firewalld
  service: name=firewalld state=stopped enabled=no

- name: install selinux bindings
  yum: name=libselinux-python state=present

- name: disable selinux
  selinux: state=disabled
